name: Build, Test e Build-Artifacts

on:
  push:
    branches:
      - Develop
  pull_request:
    branches:
      - Develop

jobs:
  test:
    name: Instalar e Rodar Testes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Node.js (v18)
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Instalar dependências (npm ci)
        run: npm ci

      - name: Rodar Testes (npm test)
        run: npm test -- --ci --coverage --reporters=default

  build:
    name:  Build e Upload de Artefatos
    runs-on: ubuntu-latest
    needs: test   # só roda se o job de "test" passar

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Node.js (v18)
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Instalar dependências (npm ci)
        run: npm ci

      - name: Build da aplicação (npm run build)
        run: npm run build

      - name: Upload dos artefatos de build
        uses: actions/upload-artifact@v3
        with:
          name: build-dist
          path: dist/
