name: Run Tests

on:
  push:
    branches:
      - Develop
  pull_request:
    branches:
      - Develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./elodrinks-frontend/elodrinks-frontend
        run: npm ci

      - name: Run tests
        working-directory: ./elodrinks-frontend/elodrinks-frontend
        run: npm test
